development:
  adapter: sqlite3
  database: 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production_database
  pool: 5
  timeout: 5000

  # ../server/data/dev.sqlite3