export const SUBTOPICS_FETCHING = 'SUBTOPICS_FETCHING';
export const CREATE_SUBTOPIC = 'CREATE_SUBTOPIC';
export const CREATE_SUBTOPIC_FAILED = 'CREATE_SUBTOPIC_FAILED';
export const FAVORITE_SUBTOPICS_FETCHED = 'FAVORITE_SUBTOPICS_FETCHED';
export const SUBTOPIC_FAVORITED = 'SUBTOPIC_FAVORITED';
export const UN_FAVORITE = 'UN_FAVORITE';
export const SUBTOPICS_FETCHED = 'SUBTOPICS_FETCHED'
export const SUBTOPICS_FAILED = 'SUBTOPICS_FAILED'